services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-app}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
  # app:
  #   build: .
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #     redis:
  #       condition: service_started
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./config:/app/config
  #     - ./storage:/app/storage
  #   command: ["/app/qbychat-vibe-coding"]
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
volumes:
  db-data:
