ALTER TABLE chats ADD COLUMN IF NOT EXISTS chat_type TEXT;
ALTER TABLE chats ADD COLUMN IF NOT EXISTS owner_id UUID NULL REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE chats ADD COLUMN IF NOT EXISTS title TEXT;